# Build and deploy workflow to CH2

name: Build and Deploy to Sandbox CH2

# auto workflow runs on these
on:
  push:
    branches: [ main ]
# allows manual trigger for workflow in Actions tab
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # somewhat global variables here
    env:
      # change this version if we want 
      EXCHANGE_VERSION_NEW: 1.0.5-SNAPSHOT
      # set dynamically below EXCHANGE_VERSION_CURRENT: 1.0.4-SNAPSHOT
      RUNTIME_APP_NAME: mule-ch2-cicd

    steps:
    # allows action to have access to the source code
    - uses: actions/checkout@v2

    # caches maven dependencies so after the first run, it'll be faster
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    # setup java in ubuntu, 1.8 aka Java 8 is the one that Mule likes atm (Jan 2023)
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # this part adds credentials maven instead of having a settings.xml file
    # quite a nice way to avoid having another file and less risky way of inserting credentials
    # turns out we don't need nexus credentials for a basic app, but likely will for paid connectors (SAP, HL7, etc)
    - name: Add credentials	
      uses: s4u/maven-settings-action@v2.4.0	
      with:	
        servers: |	
          [{
          "id": "anypoint-exchange-v3",	
           "username": "~~~Client~~~",	
           "password": "${{ secrets.MULE_CLIENT_ID }}~?~${{ secrets.MULE_CLIENT_SECRET }}"	
          },
          {	
           "id": "mule-enterprise",	
           "username": "${{ secrets.MULE_NEXUS_USERNAME }}",	
           "password": "${{ secrets.MULE_NEXUS_PASSWORD }}"	
          }]
    # an optional step to help with debugging maybe
    - name: Print effective-settings (optional)
      run: mvn help:effective-settings

    # build from the pom file
    # try set version here via revision variable
    - name: Build with Maven
      run: mvn -B package -Drevision="${{ env.EXCHANGE_VERSION_NEW }}" --file pom.xml
    
    # check version in POM file
    # trying step mvn package 
    - name: Set current version to env variable called "EXCHANGE_VERSION_CURRENT"
      run: |
        echo "EXCHANGE_VERSION_CURRENT=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    # each deploy to exchange needs an increase in version for a non-snapshot version, 
    # else it'll fail and complain that the version already exists
    # a X.X.X-SNAPSHOT version can be overwritten
    # maybe the env variables don't need ${{}} inside if statement
    - name: Deploy to Exchange if snapshot version
      if: contains(env.EXCHANGE_VERSION_NEW,'SNAPSHOT')
      run: |
        mvn deploy -Drevision="${{ env.EXCHANGE_VERSION_NEW }}"

    # avoid running twice with not contains snapshot
    - name: Deploy to Exchange if new != current version and not contains snapshot
      if: (env.EXCHANGE_VERSION_NEW != env.EXCHANGE_VERSION_CURRENT) && (!contains(env.EXCHANGE_VERSION_NEW,'SNAPSHOT'))
      run: |
        mvn deploy -Drevision="${{ env.EXCHANGE_VERSION_NEW }}"

    # if we change the APP_NAME, a new runtime is deployed
    - name: Then deploy to Sandbox
      run: |
        mvn deploy -DmuleDeploy \
         -DclientId="${{ secrets.MULE_CLIENT_ID }}" \
         -DclientSecret="${{ secrets.MULE_CLIENT_SECRET }}" \
         -DappName="${{ env.RUNTIME_APP_NAME }}" \
         -DskipTests


    # I have a feeling we don't need artifact because we're pulling from exchange
    # allows us to see which commit hash is being deployed to cloudhub
    # - name: Stamp artifact file name with commit hash
    #   run: |
    #     artifactName1=$(ls target/*.jar | head -1)
    #     commitHash=$(git rev-parse --short "$GITHUB_SHA")
    #     artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
    #     mv $artifactName1 $artifactName2
    # # using @v1 instead of @master according to github recommendations
    # # https://github.com/actions/upload-artifact/issues/41
    # - name: Upload artifact 
    #   uses: actions/upload-artifact@master
    #   with:
    #       name: artifacts
    #       path: target/*.jar
        
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:    
  #   - uses: actions/checkout@v2
    
  #   - uses: actions/cache@v1
  #     with:
  #       path: ~/.m2/repository
  #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #       restore-keys: |
  #         ${{ runner.os }}-maven-
    
  #   - uses: actions/download-artifact@master
  #     with:
  #       name: artifacts
    
  #   # - name: Deploy to Exchange
  #   #   run: |
  #   #     artifactName=$(ls *.jar | head -1)
  #   #     mvn deploy \
  #   #       -Dmule.artifact=$artifactName \
  #   #       -DskipTests


  #   - name: Then deploy to Sandbox
  #     env:
  #       CLIENT_ID: ${{ secrets.MULE_CLIENT_ID }}
  #       CLIENT_SECRET: ${{ secrets.MULE_CLIENT_SECRET }}
  #       APP_NAME: mule-ch2-cicd
  #     run: |
  #       artifactName=$(ls *.jar | head -1)
  #       mvn deploy -DmuleDeploy \
  #        -Dmule.artifact=$artifactName \
  #        -DclientId="$CLIENT_ID" \
  #        -DclientSecret="$CLIENT_SECRET" \
  #        -DappName="$APP_NAME" \
  #        -DskipTests
